export const testimonialData = [
  {
    name: "Dhruv Kotwani",
    username: "@druv_kotwani",
    icon: "https://randomuser.me/api/portraits/men/1.jpg",
    text: "It was super smooth and the whole process with QuillAudits was beyond the expectations. As a start-up we guys are looking for something genuine & QuillAudits is way ahead of our expectations.",
  },
  {
    name: "Kotwani",
    about: "Founder of Startup Samachar",
    icon: "https://randomuser.me/api/portraits/men/2.jpg",
    text: "The process was made quite simple by QuillAudits. The turnaround time was less which was favorable for us.",
  },
  {
    name: "Aarohi Sharma",
    username: "@aarohi_sharma",
    icon: "https://randomuser.me/api/portraits/women/3.jpg",
    text: "Working with QuillAudits was a breeze. Their attention to detail and professionalism are commendable. Highly recommended!",
    platform: "discord",
    date: "10 September 2023",
  },
  {
    name: "Rohan Patel",
    about: "Co-founder of TechTribe",
    icon: "https://randomuser.me/api/portraits/men/4.jpg",
    text: "Impressed by the efficiency and quality of service provided by QuillAudits. Will definitely collaborate with them again in the future.",
  },
  {
    name: "Anaya Singh",
    username: "@anaya_singh",
    icon: "https://randomuser.me/api/portraits/women/5.jpg",
    text: "QuillAudits exceeded our expectations. Their team is highly skilled and delivers results promptly. Great experience overall!",
    platform: "peerlist",
    date: "15 November 2023",
  },
  {
    name: "Priya Gupta",
    username: "@priya_gupta",
    icon: "https://randomuser.me/api/portraits/women/7.jpg",
    text: "As a small business owner, I appreciate the personalized approach of QuillAudits. They truly understand our needs and deliver accordingly.",
    platform: "twitter",
    date: "16 June 2023",
  },
  {
    name: "Aditya Desai",
    about: "CEO of Innovate Solutions",
    icon: "https://randomuser.me/api/portraits/men/8.jpg",
    text: "QuillAudits played a crucial role in optimizing our processes. Their insights were invaluable. Looking forward to future collaborations.",
    platform: "discord",
    date: "23 April 2023",
  },
  {
    name: "Neha Verma",
    username: "@neha_verma",
    icon: "https://randomuser.me/api/portraits/women/9.jpg",
    text: "Highly impressed by the professionalism of QuillAudits. They delivered results even before the deadline. Exceptional service!",
    platform: "facebook",
    date: "2 August 2023",
  },
  {
    name: "Rajesh Singh",
    about: "CTO at Tech Innovations",
    icon: "https://randomuser.me/api/portraits/men/10.jpg",
    text: "QuillAudits helped us streamline our tech infrastructure. Their expertise saved us time and resources. Definitely recommend their services.",
    platform: "twitter",
    date: "19 November 2023",
  },
  {
    name: "Alisha Shah",
    username: "@alisha_shah",
    icon: "https://randomuser.me/api/portraits/women/11.jpg",
    text: "Working with QuillAudits was a pleasure. They understood our requirements perfectly and delivered exceptional results.",
    platform: "peerlist",
    date: "7 February 2023",
  },
  {
    name: "Rajat Kapoor",
    about: "Founder of Digital Solutions Ltd.",
    icon: "https://randomuser.me/api/portraits/men/12.jpg",
    text: "QuillAudits provided valuable insights that helped us improve our digital presence. Their team is highly professional and knowledgeable.",
    platform: "discord",
    date: "15 May 2023",
  },
  {
    name: "Swati Mishra",
    username: "@swati_mishra",
    icon: "https://randomuser.me/api/portraits/women/13.jpg",
    text: "I'm thoroughly impressed by the efficiency of QuillAudits. They delivered exactly what we needed within the specified timeframe.",
    platform: "facebook",
    date: "29 July 2023",
  },
  {
    name: "Kunal Gupta",
    about: "CEO of TechGenius",
    icon: "https://randomuser.me/api/portraits/men/14.jpg",
    text: "QuillAudits provided innovative solutions that helped us stay ahead in the competitive market. Their professionalism is commendable.",
    platform: "twitter",
    date: "14 September 2023",
  },
  {
    name: "Shreya Patel",
    username: "@shreya_patel",
    icon: "https://randomuser.me/api/portraits/women/15.jpg",
    text: "QuillAudits has a dedicated team that goes above and beyond to meet client expectations. I'm extremely satisfied with their services.",
    platform: "discord",
    date: "3 March 2023",
  },
  {
    name: "Rahul Sharma",
    about: "Marketing Director at ABC Corp",
    icon: "https://randomuser.me/api/portraits/men/16.jpg",
    text: "QuillAudits helped us revamp our marketing strategy with their innovative ideas. The results were beyond our expectations.",
    platform: "peerlist",
    date: "18 October 2023",
  },
  {
    name: "Sneha Gupta",
    username: "@sneha_gupta",
    icon: "https://randomuser.me/api/portraits/women/17.jpg",
    text: "The team at QuillAudits is highly professional and responsive. They delivered excellent results within a short timeframe.",
    platform: "twitter",
    date: "25 May 2023",
  },
  {
    name: "Amit Singh",
    about: "Co-founder of Tech Innovations",
    icon: "https://randomuser.me/api/portraits/men/18.jpg",
    text: "QuillAudits provided us with valuable insights that helped us make informed decisions. Their expertise is truly commendable.",
    platform: "discord",
    date: "9 April 2023",
  },
  {
    name: "Nidhi Patel",
    username: "@nidhi_patel",
    icon: "https://randomuser.me/api/portraits/women/19.jpg",
    text: "Working with QuillAudits was a great experience. They understood our requirements perfectly and delivered exceptional results.",
    platform: "facebook",
    date: "12 August 2023",
  },
  {
    name: "Rajesh Khanna",
    about: "Founder of Tech Solutions Inc.",
    icon: "https://randomuser.me/api/portraits/men/20.jpg",
    text: "QuillAudits helped us optimize our processes, resulting in increased efficiency and productivity. Highly recommend their services.",
    platform: "discord",
    date: "17 June 2023",
  },
];
